dist: trusty
language: java
jdk:
  - openjdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
addons:
  sonarcloud:
    organization: 'jojoriveraa'
    token:
      secure: $SONAR_TOKEN
